bool connect 	# True for connecting
				# False for disconnecting

string ip		# IP address of device if connecting
---
bool result		# Assert if operation was completed
				# True if it was sucessful
				# False if not
